name: PhoneDex
options:
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: 5.9
targets:
  PhoneDex:
    type: application
    platform: iOS
    sources:
      - PhoneDexApp
    settings:
      base:
        DEVELOPMENT_TEAM: RQRRLJ37K2
        PRODUCT_BUNDLE_IDENTIFIER: com.nash226.PhoneDex
        INFOPLIST_FILE: PhoneDexApp/Info.plist
    dependencies:
      - target: PhoneDexNotificationExtension
  PhoneDexNotificationExtension:
    type: app-extension
    platform: iOS
    sources:
      - PhoneDexNotificationExtension
    settings:
      base:
        DEVELOPMENT_TEAM: RQRRLJ37K2
        PRODUCT_BUNDLE_IDENTIFIER: com.nash226.PhoneDex.NotificationExtension
        INFOPLIST_FILE: PhoneDexNotificationExtension/Info.plist
        APPLICATION_EXTENSION_API_ONLY: YES
  PhoneDexTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PhoneDexTests
    dependencies:
      - target: PhoneDex
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nash226.PhoneDexTests
        GENERATE_INFOPLIST_FILE: YES
schemes:
  PhoneDex:
    build:
      targets:
        PhoneDex: all
        PhoneDexNotificationExtension: all
        PhoneDexTests: [test]
    test:
      targets:
        - PhoneDexTests
