name: WatchDexWatch

options:
  bundleIdPrefix: com.nash226
  deploymentTarget:
    watchOS: "10.0"

settings:
  MARKETING_VERSION: 0.1.0
  CURRENT_PROJECT_VERSION: 1
  SWIFT_VERSION: 6.0

targets:
  WatchDex Watch App:
    type: application.watchapp2
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - WatchDexWatchApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nash226.WatchDex.watchkitapp
      INFOPLIST_FILE: WatchDexWatchApp/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
